### ISSUE TITLE
依赖问题

### ISSUE THREAD

**Issue by Sourcefuture** [jsun969/uwall#22]
我尝试在replit上部署该项目 在执行命令“pnpm run db:seed”时发生错误

~/NodejsProject/uwall$ pnpm run db:seed

> uwall@0.0.6 db:seed /home/runner/NodejsProject/uwall
> cross-env SKIP_ENV_VALIDATION=true tsx ./seed.ts

prisma:error 
Invalid `prisma.config.findFirst()` invocation:

Unable to require(`/home/runner/NodejsProject/uwall/node_modules/.pnpm/@prisma+client@5.5.2_prisma@5.5.2/node_modules/.prisma/client/libquery_engine-debian-openssl-1.1.x.so.node`).
Prisma cannot find the required `libssl` system library in your system. Please install openssl-1.1.x and try again.

Details: libssl.so.1.1: cannot open shared object file: No such file or directory

/home/runner/NodejsProject/uwall/node_modules/.pnpm/@prisma+client@5.5.2_prisma@5.5.2/node_modules/@prisma/client/runtime/library.js:123

请问如何解决libssl.so.1.1的依赖问题或使用其他包来代替

**Comment by jsun969** [comment]
可能 replit 上是无法部署的，需要数据库吧？

**Comment by Sourcefuture** [comment]
好的 感谢
